// react-version/src/components/HomeView.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function HomeView({ countries }) {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRegion, setSelectedRegion] = useState('');
  const [dropdownOpen, setDropdownOpen] = useState(false);

  // Toggle custom dropdown
  const toggleDropdown = () => setDropdownOpen(prev => !prev);

  // Select a region option
  const selectRegion = (region) => {
    setSelectedRegion(region);
    setDropdownOpen(false);
  };

  // Close dropdown on click outside can be added via hook, but standard toggle is already robust
  const handleDropdownBlur = () => {
    // Timeout allows option click event to fire before dropdown closes
    setTimeout(() => {
      setDropdownOpen(false);
    }, 200);
  };

  // Combined Searching & Filtering Logic
  const filteredCountries = countries.filter(country => {
    const matchesSearch = country.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesRegion = selectedRegion === '' || country.region === selectedRegion;
    return matchesSearch && matchesRegion;
  });

  return (
    <div>
      {/* Search and Filter Controls */}
      <div className="controls-row">
        {/* Search Input Container */}
        <div className="search-container">
          <i className="fa-solid fa-magnifying-glass"></i>
          <input
            type="text"
            className="search-input"
            placeholder="Search for a country..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            autoComplete="off"
          />
        </div>

        {/* Custom styled Region Dropdown Container */}
        <div className="filter-container" onBlur={handleDropdownBlur}>
          <button
            className="filter-btn"
            onClick={toggleDropdown}
            aria-haspopup="listbox"
            aria-expanded={dropdownOpen}
          >
            <span>{selectedRegion ? selectedRegion : 'Filter by Region'}</span>
            <i className="fa-solid fa-chevron-down"></i>
          </button>

          <ul className={`filter-options ${dropdownOpen ? 'show' : ''}`} role="listbox">
            <li className="filter-option" onClick={() => selectRegion('')} role="option">All Regions</li>
            <li className="filter-option" onClick={() => selectRegion('Africa')} role="option">Africa</li>
            <li className="filter-option" onClick={() => selectRegion('Americas')} role="option">Americas</li>
            <li className="filter-option" onClick={() => selectRegion('Asia')} role="option">Asia</li>
            <li className="filter-option" onClick={() => selectRegion('Europe')} role="option">Europe</li>
            <li className="filter-option" onClick={() => selectRegion('Oceania')} role="option">Oceania</li>
          </ul>
        </div>
      </div>

      {/* Countries Cards Grid */}
      <div className="countries-grid">
        {filteredCountries.length === 0 ? (
          <div className="grid-empty-state">
            No countries match your search criteria.
          </div>
        ) : (
          filteredCountries.map(country => (
            <div
              key={country.code}
              className="card"
              role="link"
              tabIndex={0}
              onClick={() => navigate(`/country/${country.code}`)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') navigate(`/country/${country.code}`);
              }}
            >
              <div className="card__flag-wrapper">
                <img className="card__flag" src={country.flag} alt={`${country.name} Flag`} loading="lazy" />
              </div>
              <div className="card__info">
                <h2 className="card__name">{country.name}</h2>
                <ul className="card__details">
                  <li><strong>Population:</strong> {country.population.toLocaleString()}</li>
                  <li><strong>Region:</strong> {country.region}</li>
                  <li><strong>Capital:</strong> {country.capital}</li>
                </ul>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

export default HomeView;

// vue-version/src/components/HomeView.vue
<template>
  <div>
    <!-- Search and Filter Controls -->
    <div class="controls-row">
      <!-- Search Input Container -->
      <div class="search-container">
        <i class="fa-solid fa-magnifying-glass"></i>
        <input 
          type="text" 
          class="search-input" 
          placeholder="Search for a country..." 
          v-model="searchQuery"
          autocomplete="off"
        />
      </div>

      <!-- Custom styled Region Dropdown Container -->
      <div class="filter-container" @focusout="handleBlur">
        <button 
          class="filter-btn" 
          @click="toggleDropdown"
          aria-haspopup="listbox" 
          :aria-expanded="dropdownOpen"
        >
          <span>{{ selectedRegion ? selectedRegion : 'Filter by Region' }}</span>
          <i class="fa-solid fa-chevron-down"></i>
        </button>
        
        <ul class="filter-options" :class="{ show: dropdownOpen }" role="listbox">
          <li class="filter-option" @click="selectRegion('')" role="option">All Regions</li>
          <li class="filter-option" @click="selectRegion('Africa')" role="option">Africa</li>
          <li class="filter-option" @click="selectRegion('Americas')" role="option">Americas</li>
          <li class="filter-option" @click="selectRegion('Asia')" role="option">Asia</li>
          <li class="filter-option" @click="selectRegion('Europe')" role="option">Europe</li>
          <li class="filter-option" @click="selectRegion('Oceania')" role="option">Oceania</li>
        </ul>
      </div>
    </div>

    <!-- Countries Cards Grid -->
    <div class="countries-grid">
      <div 
        v-if="filteredCountries.length === 0" 
        class="grid-empty-state"
      >
        No countries match your search criteria.
      </div>
      
      <div 
        v-else 
        v-for="country in filteredCountries" 
        :key="country.code" 
        class="card" 
        role="link" 
        tabindex="0"
        @click="goToDetail(country.code)"
        @keydown.enter="goToDetail(country.code)"
      >
        <div class="card__flag-wrapper">
          <img class="card__flag" :src="country.flag" :alt="country.name + ' Flag'" loading="lazy" />
        </div>
        <div class="card__info">
          <h2 class="card__name">{{ country.name }}</h2>
          <ul class="card__details">
            <li><strong>Population:</strong> {{ country.population.toLocaleString() }}</li>
            <li><strong>Region:</strong> {{ country.region }}</li>
            <li><strong>Capital:</strong> {{ country.capital }}</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, inject, computed } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

// Inject the global reactive countries state provided by App.vue
const countries = inject('countries', ref([]));

// Stateful filtering parameters
const searchQuery = ref('');
const selectedRegion = ref('');
const dropdownOpen = ref(false);

const toggleDropdown = () => {
  dropdownOpen.value = !dropdownOpen.value;
};

const selectRegion = (region) => {
  selectedRegion.value = region;
  dropdownOpen.value = false;
};

// Close dropdown on click outside
const handleBlur = (e) => {
  // Timeout allows the option click event to fire before dropdown closes
  setTimeout(() => {
    dropdownOpen.value = false;
  }, 200);
};

// Combined Searching & Filtering Computed Property
const filteredCountries = computed(() => {
  if (!countries.value) return [];
  return countries.value.filter(country => {
    const matchesSearch = country.name.toLowerCase().includes(searchQuery.value.toLowerCase());
    const matchesRegion = selectedRegion.value === '' || country.region === selectedRegion.value;
    return matchesSearch && matchesRegion;
  });
});

const goToDetail = (code) => {
  router.push(`/country/${code}`);
};
</script>
